server:
  port: 8080
spring:
  application:
    name: symphony
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-bp13g1e5582hml10juo.mysql.rds.aliyuncs.com:3306/b3log_symphony?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: symphony
    password: AZ5%lizIUuCl9pUu
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/WEB-INF/static/
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    parser:
      allow_single_quotes: true
      allow_unquoted_control_chars: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    prefix: classpath:/WEB-INF/templates/
    suffix: .html
  properties:
    symphony:
      static-path: http://127.0.0.1:8080/static
      upload-path: http://127.0.0.1:8080/upload

